# Generated by Django 3.1.3 on 2020-12-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodzaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaklady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Surowce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=30)),
                ('ilosc', models.IntegerField(default=0)),
                ('rodzaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surowce_rodzaj', to='rodzprod.rodzaje')),
            ],
        ),
        migrations.AddField(
            model_name='rodzaje',
            name='zaklady',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodzaje_zaklady', to='rodzprod.zaklady'),
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=30)),
                ('poziom', models.IntegerField(default=0)),
                ('idr', models.IntegerField(default=0)),
                ('rodzaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty_rodzaj', to='rodzprod.rodzaje')),
            ],
        ),
        migrations.CreateModel(
            name='Narzedzia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=30)),
                ('aktywnosc', models.IntegerField(default=0)),
                ('rodzaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narzedzia_rodzaj', to='rodzprod.rodzaje')),
            ],
        ),
    ]
